# Generated by Django 5.0.4 on 2024-05-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payments_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
