# Generated by Django 5.0.4 on 2024-05-08 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_rename_payments_subscription'),
        ('users', '0005_delete_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_pay', models.CharField(choices=[('cash', 'наличными'), ('card', 'картой')], max_length=15)),
                ('date_payment', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('money', models.IntegerField()),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату')),
                ('lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('well', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.well')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
