# Generated by Django 5.0.4 on 2024-05-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_rename_payments_subscription'),
        ('users', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.lesson'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms.well'),
        ),
    ]
