# Generated by Django 5.0.4 on 2024-05-08 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Subscription',
        ),
    ]
